#!/bin/sh

DIR=$(dirname $0)

main() {
	db="$1"

	until echo "$amount" | grep -Eq '^[0-9]+$'; do
		printf "am? "
		read amount

		if [ "$amount" = "qq" ]; then
			exit
		fi
	done

	echo "select printf('am: %.2f', cast($amount as real) / 100)" | sqlite3

	until grep -Fqx "$to" $DIR/config/accepted_to; do
		printf "to? "
		read to

		if [ "$to" = "qq" ]; then
			exit
		fi
	done

	until grep -Fqx "$from" $DIR/config/accepted_from; do
		printf "fr? "
		read from

		if [ "$from" = "qq" ]; then
			exit
		fi
	done

	until [ -n "$comment" ]; do
		printf "co? "
		read comment

		if [ "$comment" = "qq" ]; then
			exit
		fi
	done

	while :; do
		default_date=$(echo "select date()" | sqlite3)

		printf "da? ($default_date) "
		read date

		if [ "$date" = "qq" ]; then
			exit
		fi

		if echo "$date" | grep -q '^d$'; then
			date="$default_date"
			break
		fi

		if echo "$date" | grep -Eq '^[0-3][0-9]([a-z]{3}([0-9]{1,})?)?$'; then
			date=$(sh $DIR/parse_date "$date")
			break
		fi

		echo
		echo "examples:"
		echo "d          default date"
		echo "31dec2025  2025-12-31"
		echo "31dec      2025-12-31"
		echo "31         2025-12-31"
		echo
	done

	echo "da: $date"

	sqlite3 "$db" <<EOD
insert into t (d, a, f, t, c) values (
	'$date',
	$amount,
	'$(escape_quotes "$from")',
	'$(escape_quotes "$to")',
	'$(escape_quotes "$comment")'
);

select last_insert_rowid();
EOD

	echo
	sh $DIR/select "$db" "$date"
}

escape_quotes() {
	echo "$@" | sed "s/'/''/g"
}

main "$@"
