#!/bin/sh

main() {
	DIR=$(dirname $0)

	. $DIR/config/main.sh

	if [ "$DB" = "" ]; then
		printf "Error: DB not configured"
		exit 1
	fi

	printf "am? "
	read amount

	printf "to? "
	read to

	printf "fr? "
	read from

	printf "co? "
	read comment

	printf "da? "
	read date

	date=$(sh $DIR/parse_date "$date")

	sqlite3 "$DB" <<EOD
insert into t (d, a, f, t, c) values (
	'$date',
	$amount,
	'$(escape_quotes "$from")',
	'$(escape_quotes "$to")',
	'$(escape_quotes "$comment")'
);

select last_insert_rowid();
EOD
}

escape_quotes() {
	sed "s/'/''/g" <<< "$@"
}

main
