#!/bin/sh

DIR=$(dirname $0)

main() {
	db="$1"

	until echo "$amount" | grep -Eq '^[0-9]+$'; do
		printf "am? "
		read amount

		if [ "$amount" = "qq" ]; then
			exit
		fi
	done

	until grep -Fqx "$to" $DIR/config/accepted_to; do
		printf "to? "
		read to

		if [ "$to" = "qq" ]; then
			exit
		fi
	done

	until grep -Fqx "$from" $DIR/config/accepted_from; do
		printf "fr? "
		read from

		if [ "$from" = "qq" ]; then
			exit
		fi
	done

	until [ -n "$comment" ]; do
		printf "co? "
		read comment

		if [ "$comment" = "qq" ]; then
			exit
		fi
	done

	printf "da? "
	read date

	if [ "$date" = "qq" ]; then
		exit
	fi

	date=$(sh $DIR/parse_date "$date")

	sqlite3 "$db" <<EOD
insert into t (d, a, f, t, c) values (
	'$date',
	$amount,
	'$(escape_quotes "$from")',
	'$(escape_quotes "$to")',
	'$(escape_quotes "$comment")'
);

select last_insert_rowid();
EOD

	echo
	sh $DIR/select "$db" "$date"
}

escape_quotes() {
	echo "$@" | sed "s/'/''/g"
}

main "$@"
