#!/bin/sh

DIR=$(dirname $0)

help() {
	cat <<EOD
usage: tx <command> [<args>]

commands:
    a    Add tx
    l    List txs
    s    Statement
    u    Update tx

usage: tx l [<date>]
examples:
    $ tx l 2000-12-31
    $ tx l 31
    $ tx l 31dec
    $ tx l 31dec2025
    $ tx l f  # future

usage: tx s <from> <day> [<month> [<year>]]
examples:
    $ tx s one 01
    $ tx s one 01 12
    $ tx s one 01 12 2025
EOD
}

main() {
	. $DIR/config/main.sh

	if [ "$DB" = "" ]; then
		printf "Error: DB not configured"
		exit 1
	fi

	case "$1" in
		a)
			sh $DIR/insert "$DB"
			;;
		l)
			sh $DIR/select "$DB" "$2"
			;;
		s)
			shift
			sh $DIR/statement "$DB" "$@"
			;;
		u)
			sh $DIR/update "$DB"
			;;
		*)
			help
			exit 1
			;;
	esac
}

main "$@"
