#!/bin/sh

help() {
	cat <<EOD
usage: tx <command> [<args>]

commands:
    a             Add tx
    l [<date>]    List txs

examples:
    $ tx l 2000-12-31
    $ tx l 31
    $ tx l 31dec
    $ tx l 31dec2025
EOD
}

main() {
	DIR=$(dirname $0)

	case "$1" in
		a)
			sh $DIR/insert_or_update
			;;
		l)
			sh $DIR/select "$2"
			;;
		*)
			help
			exit 1
			;;
	esac
}

main "$@"
