#!/bin/sh

DIR=$(dirname $0)

help() {
	cat <<EOD
usage: tx <command> [<args>]

commands:
    a             Add tx
    l [<date>]    List txs
    u             Update tx

examples:
    $ tx l 2000-12-31
    $ tx l 31
    $ tx l 31dec
    $ tx l 31dec2025
EOD
}

main() {
	. $DIR/config/main.sh

	if [ "$DB" = "" ]; then
		printf "Error: DB not configured"
		exit 1
	fi

	case "$1" in
		a)
			sh $DIR/insert "$DB"
			;;
		l)
			sh $DIR/select "$DB" "$2"
			;;
		u)
			sh $DIR/update "$DB"
			;;
		*)
			help
			exit 1
			;;
	esac
}

main "$@"
