#!/bin/sh

# examples:
# 	parse_date "2000-12-31"
# 	parse_date "31dec2000"
# 	parse_date "31dec"
# 	parse_date "31"

main() {
	if echo "$1" | grep -Eq '^[0-9]+-[0-9]{2}-[0-9]{2}$'; then
		echo "$1"
		exit 0
	fi

	sqlite3 <<EOD
with
a as (
	select '$1' as input
),
b as (
	select
		substr(input, 1, 2) as day,
		substr(input, 3, 3) as month,
		substr(input, 6) as year
	from a
),
c as (
	select
		case
			when length(day) = 2 then
				day
			else
				strftime('%d', 'now')
		end as day,
		case month
			when 'jan' then '01'
			when 'feb' then '02'
			when 'mar' then '03'
			when 'apr' then '04'
			when 'may' then '05'
			when 'jun' then '06'
			when 'jul' then '07'
			when 'aug' then '08'
			when 'sep' then '09'
			when 'oct' then '10'
			when 'nov' then '11'
			when 'dec' then '12'
			else strftime('%m', 'now')
		end as month,
		case
			when length(year) > 0 then
				year
			else
				strftime('%Y', 'now')
		end as year
	from b
)
select
	printf('%s-%s-%s', year, month, day)
from c;
EOD
}

main "$@"
