#!/bin/sh

# Examples
# ./parse_date "01jan2025"
# ./parse_date "01jan"
# ./parse_date "01"

main() {
	sqlite3 <<EOD
with
a as (
	select '$1' as input
),
b as (
	select
		substr(input, 1, 2) as day,
		substr(input, 3, 3) as month,
		substr(input, 6) as year
	from a
),
c as (
	select
		case length(day)
			when 2 then day
			else strftime('%d', 'now')
		end as day,
		case month
			when 'jan' then '01'
			when 'feb' then '02'
			when 'mar' then '03'
			when 'apr' then '04'
			when 'may' then '05'
			when 'jun' then '06'
			when 'jul' then '07'
			when 'aug' then '08'
			when 'sep' then '09'
			when 'oct' then '10'
			when 'nov' then '11'
			when 'dec' then '12'
			else strftime('%m', 'now')
		end as month,
		case length(year)
			when 0 then strftime('%Y', 'now')
			else year
		end as year
	from b
)
select
	printf('%s-%s-%s', year, month, day)
from c;
EOD
}

main "$@"
