#!/bin/sh

DIR=$(dirname $0)

main() {
	db="$1"
	s="$2"

	if [ "$s" = "f" ]; then
		where="d > date()"
		echo "Future"
	else
		date=$(sh $DIR/parse_date "$s")
		where="d = '$date'"
		echo $date
	fi

	sqlite3 "$db" <<EOD
.mode column

.width -8 10 10 15

select
	printf('%.2f', a / 100.0) as a,
	f,
	t,
	substr(c, 1, 15) as c,
	oid
from t
where $where
order by oid;
EOD
}

main "$@"
