#!/bin/sh

DIR=$(dirname $0)

main() {
	db="$1"

	sqlite3 "$db" <<EOD
.mode column
.header off

.width 10 -7 35

select
	d,
	printf('%.2f', a / 100.0),
	printf('%s -> %s (%s)', f, t, substr(c, 1, 15))
from t
where d > date()
order by d, oid;
EOD
}

main "$@"
