#!/bin/sh

DIR=$(dirname $0)

main() {
	db="$1"

	sqlite3 "$db" <<EOD
.mode column

.width 10 -8 10 10 15

select
	d,
	printf('%.2f', a / 100.0) as a,
	f,
	t,
	substr(c, 1, 15) as c,
	oid
from t
where d > date()
order by d, oid;
EOD
}

main "$@"
